# Node.js


# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12'
  displayName: 'Install Node.js'

- script: |
    npm install
    npx playwright install
    ./node_modules/.bin/cucumber-js --require cucumber.conf.js --format json:./reports/report.json --require tests/step_definitions/*.js tests/features/*.feature
    node report_html.js
    cd reports
    cd cucumber-htmlreport.html
  displayName: 'Run automation test'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'reports'
    artifact: 'Publish report'
    publishLocation: 'pipeline'
